### ISSUE TITLE
Support sub paths

### ISSUE THREAD

**Issue by amorenew** [littleGnAl/assets-scanner#17]
I organize my assets like assets/images, assets/fonts,
So I wonder if sub-paths are supported?

**Comment by littleGnAl** [comment]
Hi @amorenew
Here's the PR why I remove this support. https://github.com/littleGnAl/assets-scanner/pull/10

**Comment by amorenew** [comment]
@littleGnAl Thank you, I found the solution I just need to add "/" at the end
I wonder if I could get more classes for different types like 
MainAssets, FontAssets, ImageAssets, SoundAssets
Or like Android R.drawable.logo.png

**Comment by amorenew** [comment]
@littleGnAl I found it generated as subfolder_name.png
That's very cool
