### ISSUE TITLE
single quotes

### ISSUE THREAD

**Issue by amorenew** [littleGnAl/assets-scanner#18]
I wonder if you could use single quotes on the generated file or adding ignore single quotes 
`    // ignore: avoid_single_cascade_in_expression_statements
`

**Comment by littleGnAl** [comment]
@amorenew It actually with some issue of the `ignore_for_file`, I will fix it these few days.

**Comment by littleGnAl** [comment]
@amorenew  Pls try  version`1.1.1`.

**Comment by amorenew** [comment]
@littleGnAl Very cool, It is working as expected.
Thanks a lot
