### ISSUE TITLE
Upgrade to analyzer ^0.40.1

### ISSUE THREAD

**Issue by ldasilva-net** [littleGnAl/assets-scanner#20]
Hi, today the lib depends on `analyzer ^0.39.4` but last build_runner use `analyzer ^0.40.1`. 
Do you can release a new version with new analyzer depends?
Thanks!

**Comment by littleGnAl** [comment]
@ldasilva-net I finally remove the unnecessarily `analyzer` dependencies and release a new version, pls try `assets_scanner: ^1.1.2`.

**Comment by ldasilva-net** [comment]
It works perfect. Thanks a lot!
