### ISSUE TITLE
Hopefully it can ignore the 2.0x image

### ISSUE THREAD

**Issue by songhuaixu** [littleGnAl/assets-scanner#24]
Hopefully it can ignore the 2.0x image

**Comment by littleGnAl** [comment]
Hello @SongHuaixu ,
`asset_scanner` intends to follow [official guidelines ](https://flutter.dev/docs/development/ui/assets-and-images#loading-images-1) and will respect any value you add under the `assets`(although special characters will be modified). If you add a 2.0x image, it will generate the corresponding path for you.
